In [62]:
import pandas as pd 
from sklearn.preprocessing import LabelBinarizer, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC

In [16]:
train ="model/data/train.csv"
df = pd.read_csv(train)

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df = df.drop(['PassengerId','Name','Ticket','Embarked','Cabin'], axis=1)

In [23]:
df = df.fillna(method='ffill')
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [24]:
df.isnull()

     Survived  Pclass    Sex    Age  SibSp  Parch   Fare
0       False   False  False  False  False  False  False
1       False   False  False  False  False  False  False
2       False   False  False  False  False  False  False
3       False   False  False  False  False  False  False
4       False   False  False  False  False  False  False
5       False   False  False  False  False  False  False
6       False   False  False  False  False  False  False
7       False   False  False  False  False  False  False
8       False   False  False  False  False  False  False
9       False   False  False  False  False  False  False
10      False   False  False  False  False  False  False
11      False   False  False  False  False  False  False
12      False   False  False  False  False  False  False
13      False   False  False  False  False  False  False
14      False   False  False  False  False  False  False
15      False   False  False  False  False  False  False
16      False   False  False  False  False  False  False
17      False   False  False  False  False  False  False
18      False   False  False  False  False  False  False
19      False   False  False  False  False  False  False
20      False   False  False  False  False  False  False
21      False   False  False  False  False  False  False
22      False   False  False  False  False  False  False
23      False   False  False  False  False  False  False
24      False   False  False  False  False  False  False
25      False   False  False  False  False  False  False
26      False   False  False  False  False  False  False
27      False   False  False  False  False  False  False
28      False   False  False  False  False  False  False
29      False   False  False  False  False  False  False
..        ...     ...    ...    ...    ...    ...    ...
861     False   False  False  False  False  False  False
862     False   False  False  False  False  False  False
863     False   False  False  False  False  False  False
864     False   False  False  False  False  False  False
865     False   False  False  False  False  False  False
866     False   False  False  False  False  False  False
867     False   False  False  False  False  False  False
868     False   False  False  False  False  False  False
869     False   False  False  False  False  False  False
870     False   False  False  False  False  False  False
871     False   False  False  False  False  False  False
872     False   False  False  False  False  False  False
873     False   False  False  False  False  False  False
874     False   False  False  False  False  False  False
875     False   False  False  False  False  False  False
876     False   False  False  False  False  False  False
877     False   False  False  False  False  False  False
878     False   False  False  False  False  False  False
879     False   False  False  False  False  False  False
880     False   False  False  False  False  False  False
881     False   False  False  False  False  False  False
882     False   False  False  False  False  False  False
883     False   False  False  False  False  False  False
884     False   False  False  False  False  False  False
885     False   False  False  False  False  False  False
886     False   False  False  False  False  False  False
887     False   False  False  False  False  False  False
888     False   False  False  False  False  False  False
889     False   False  False  False  False  False  False
890     False   False  False  False  False  False  False

[891 rows x 7 columns]

In [31]:
lb = LabelBinarizer()
df['Sex'] = lb.fit_transform(df['Sex'])

In [32]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [33]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [44]:
#sc = StandardScaler()
#X = sc.fit_transform(X)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [48]:
print(X)

[[ 0.82737724  0.73769513 -0.52119766  0.43279337 -0.47367361 -0.50244517]
 [-1.56610693 -1.35557354  0.57872934  0.43279337 -0.47367361  0.78684529]
 [ 0.82737724 -1.35557354 -0.24621591 -0.4745452  -0.47367361 -0.48885426]
 ...
 [ 0.82737724 -1.35557354 -0.72743397  0.43279337  2.00893337 -0.17626324]
 [-1.56610693  0.73769513 -0.24621591 -0.4745452  -0.47367361 -0.04438104]
 [ 0.82737724  0.73769513  0.16625671 -0.4745452  -0.47367361 -0.49237783]]

In [50]:
lr = LogisticRegression(penalty='l2',verbose=1)

In [51]:
lr.fit(X,y)

[LibLinear]

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=1, warm_start=False)

In [52]:
print(lr.score(X,y))

0.792368125701459

In [56]:
lrc = LogisticRegressionCV()
lrc.fit(X,y)
lrc.score(X,y)

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

0.792368125701459

In [61]:
sv = SVC()
sv.fit(X,y)
sv.score(X,y)

0.8383838383838383

In [64]:
lsv = LinearSVC(penalty='l1')
lsv.fit(X,y)
lsv.score(X,y)

ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' are not supported when dual=True, Parameters: penalty='l1', loss='squared_hinge', dual=True

In [70]:
import numpy as np
data = np.array([3,1,22,1,0,7.25])
data = data.reshape(1, -1)
sv.predict(data)

array([0])

In [ ]:
import pickle